version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/lemontech_events
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development

  test:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rspec"
    volumes:
      - .:/lemontech_events
    depends_on:
      - db
    environment:
      RAILS_ENV: test

volumes:
  postgres_data:
